Exception on /gm/gmtools/check_announcement [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/zouyang/PycharmProjects/GMTools_Flask/route.py", line 137, in gm_tools_check_announcement
    text = cdn_updater.get_file('NoticeBoardDescData.json')
  File "/Users/zouyang/PycharmProjects/GMTools_Flask/cdnUpdater.py", line 51, in get_file
    if self.refresh_url[key]:
KeyError: 'NoticeBoardDescData'
